---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{name}}-guestbook"
      namespace: argocd
    spec:
      destination:
        server: "{{server}}"
        namespace: rollouts-demo
      project: default
      source:
        repoURL: https://github.com/frealmyr/argo-poc-manifests
        path: rollouts-demo/guestbook
        targetRevision: main
        helm:
          releaseName: guestbook
          valueFiles:
            - values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
